{% set name = "ConfigSpace" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ConfigSpace-{{ version }}.tar.gz
  sha256: 57b5b8e28ed6ee14ecf6206fdca43ca698ef63bc1531f081d482b26acf4edf1a

build:
  number: 0
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - typing-extensions
    - python
    - {{ pin_compatible('numpy') }}
    - pyparsing
    - scipy
    - typing_extensions
    - more-itertools

test:
  imports:
    - ConfigSpace
    - ConfigSpace.nx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfeurer
    - BastianZim
